### ISSUE TITLE
Cafe Tokens

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-go#497]
## Description
We are transitioning Textile Cafes to using access tokens to help limit which clients are able to register with a given Cafe. This Epic is largely driven by the need to 'protect' potential Cafe deployments from unknown users registering with their Cafe for backup, recovery, etc. It is also useful for our own deployment of Cafes, to limit attacks etc. This Epic requires implementing token create, delete, list, and validation on the Cafe side, as well as a check at registration. It also requires updates to the react-native-sdk, textile-mobile client code, and for real-world deployment, the textile-opts scripts. This epic will affect internal and external Textile devs.

## Initiative / goal
This is also a step towards Cafe Pin Tracking, and should help with planned developer outreach activities.

### Hypothesis
This Epic will enable new use-cases for Textile Cafes. Success will be measured in the successful deployment and use of tokens in our real-world Textile Photos network.

## Acceptance criteria and must have scope
- [x] Updated token methods on textile-go
- [x] Updated REST + cli APIs
- [x] Updated cafe registration method
- [x] Updated cafe registration handler
- [x] Updated textile-mobile methods
- [x] Updated react-native-sdk methods
- [x] Updated textile-opts deployment and update scripts

## Stakeholders
@sanderpick (affects textile-go and textile-opts) @asutula (affects textile-mobile and react-native-sdk) @andrewxhill (affects react-native-sdk and comms).

## Timeline
This Epic is mostly already done, scoped, and prepared. Timeline is 1 additional day for review, approval, and deployment.
